"""
PDF report generation for Chest X-ray CDSS.
"""
from pathlib import Path
from fpdf import FPDF
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


class CDSSReport(FPDF):
    def header(self):
        self.set_font("Arial", "B", 10)
        self.cell(0, 8, "Chest X-ray CDSS - Clinical Decision Support Report", 0, 1, "C")
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", 0, 0, "C")


def generate_report(output_path, patient_info, predictions, class_names,
                    heatmap_path=None, original_image_path=None):
    pdf = CDSSReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Diagnostic Report", 0, 1)
    pdf.ln(4)

    pdf.set_font("Arial", "", 11)
    for key, val in patient_info.items():
        pdf.cell(0, 8, f"{key}: {val}", 0, 1)

    pdf.ln(4)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Prediction Results", 0, 1)
    pdf.set_font("Arial", "", 11)

    pred_idx = int(np.argmax(predictions))
    for i, (name, p) in enumerate(zip(class_names, predictions)):
        marker = " <--" if i == pred_idx else ""
        pdf.cell(0, 8, f"  {name}: {p:.1%}{marker}", 0, 1)

    pdf.ln(4)
    pdf.set_font("Arial", "I", 9)
    pdf.multi_cell(0, 6,
                   "Disclaimer: This report is generated by an AI decision support "
                   "system for screening purposes. It does NOT replace a formal "
                   "radiologist interpretation. Always consult a qualified physician.")

    pdf.output(str(output_path))
    return output_path
